package com.tgourouza.library_backend.constant;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum DataLanguage {
    AFRIKAANS("Afrikaans"),
    ALBANIAN("Albanian"),
    ARABIC("Arabic"),
    ARMENIAN("Armenian"),
    AZERBAIJANI("Azerbaijani"),
    BASQUE("Basque"),
    BELARUSIAN("Belarusian"),
    BENGALI("Bengali"),
    BOKMAL("Norwegian Bokmål"),
    BOSNIAN("Bosnian"),
    BULGARIAN("Bulgarian"),
    CATALAN("Catalan"),
    CHINESE("Chinese"),
    CROATIAN("Croatian"),
    CZECH("Czech"),
    DANISH("Danish"),
    DUTCH("Dutch"),
    ENGLISH("English"),
    ESPERANTO("Esperanto"),
    ESTONIAN("Estonian"),
    FINNISH("Finnish"),
    FRENCH("French"),
    GANDA("Luganda"),
    GEORGIAN("Georgian"),
    GERMAN("German"),
    GREEK("Greek"),
    GUJARATI("Gujarati"),
    HEBREW("Hebrew"),
    HINDI("Hindi"),
    HUNGARIAN("Hungarian"),
    ICELANDIC("Icelandic"),
    INDONESIAN("Indonesian"),
    IRISH("Irish"),
    ITALIAN("Italian"),
    JAPANESE("Japanese"),
    KAZAKH("Kazakh"),
    KOREAN("Korean"),
    LATIN("Latin"),
    LATVIAN("Latvian"),
    LITHUANIAN("Lithuanian"),
    MACEDONIAN("Macedonian"),
    MALAY("Malay"),
    MAORI("Māori"),
    MARATHI("Marathi"),
    MONGOLIAN("Mongolian"),
    NYNORSK("Norwegian Nynorsk"),
    PERSIAN("Persian"),
    POLISH("Polish"),
    PORTUGUESE("Portuguese"),
    PUNJABI("Punjabi"),
    ROMANIAN("Romanian"),
    RUSSIAN("Russian"),
    SERBIAN("Serbian"),
    SHONA("Shona"),
    SLOVAK("Slovak"),
    SLOVENE("Slovene"),
    SOMALI("Somali"),
    SOTHO("Sotho"),
    SPANISH("Spanish"),
    SWAHILI("Swahili"),
    SWEDISH("Swedish"),
    TAGALOG("Tagalog"),
    TAMIL("Tamil"),
    TELUGU("Telugu"),
    THAI("Thai"),
    TSONGA("Tsonga"),
    TSWANA("Tswana"),
    TURKISH("Turkish"),
    UKRAINIAN("Ukrainian"),
    URDU("Urdu"),
    VIETNAMESE("Vietnamese"),
    WELSH("Welsh"),
    XHOSA("Xhosa"),
    YORUBA("Yoruba"),
    ZULU("Zulu"),
    UNKNOWN("Unknown");

    @Getter
    private final String value;
}
