INSERT INTO status (
  english, french, spanish, italian, german, portuguese, russian, japanese
) SELECT * FROM (VALUES
  ('Unread',  'Non lu',            'No leído',  'Non letto',   'Ungelesen', 'Não lido',  'Непрочитано', '未読'),
  ('To read', 'À lire',            'Por leer',  'Da leggere',  'Zu lesen',  'Para ler',  'К прочтению', '読む予定'),
  ('Reading', 'En cours de lecture','Leyendo',  'In lettura',  'Am Lesen',  'Lendo',     'Читаю',       '読書中'),
  ('Read',    'Lu',                'Leído',     'Letto',       'Gelesen',   'Lido',      'Прочитано',   '読了')
) AS v(english,french,spanish,italian,german,portuguese,russian,japanese)
WHERE NOT EXISTS (SELECT 1 FROM status);

INSERT INTO book_tag (
  english, french, spanish, italian, german, portuguese, russian, japanese
) SELECT * FROM (VALUES
  ('Literature',        'Littérature',        'Literatura',        'Letteratura',     'Literatur',        'Literatura',          'Литература',            '文学'),
  ('Philosophy',        'Philosophie',        'Filosofía',         'Filosofia',       'Philosophie',      'Filosofia',           'Философия',             '哲学'),
  ('Religion',          'Religion',           'Religión',          'Religione',       'Religion',         'Religião',            'Религия',               '宗教'),
  ('History',           'Histoire',           'Historia',          'Storia',          'Geschichte',       'História',            'История',               '歴史'),
  ('Geography',         'Géographie',         'Geografía',         'Geografia',       'Geografie',        'Geografia',           'География',             '地理'),
  ('Social',            'Social',             'Social',            'Sociale',         'Soziales',         'Social',              'Социальное',            '社会'),
  ('Culture',           'Culture',            'Cultura',           'Cultura',         'Kultur',           'Cultura',             'Культура',              '文化'),
  ('Sociology',         'Sociologie',         'Sociología',        'Sociologia',      'Soziologie',       'Sociologia',          'Социология',            '社会学'),
  ('Politics',          'Politique',          'Política',          'Politica',        'Politik',          'Política',            'Политика',              '政治'),
  ('Mythology',         'Mythologie',         'Mitología',         'Mitologia',       'Mythologie',       'Mitologia',           'Мифология',             '神話'),
  ('Legend',            'Légende',            'Leyenda',           'Leggenda',        'Legende',          'Lenda',               'Легенда',               '伝説'),
  ('Psychology',        'Psychologie',        'Psicología',        'Psicologia',      'Psychologie',      'Psicologia',          'Психология',            '心理学'),
  ('Technology',        'Technologie',        'Tecnología',        'Tecnologia',      'Technologie',      'Tecnologia',          'Технологии',            '技術'),
  ('Science',           'Science',            'Ciencia',           'Scienza',         'Wissenschaft',     'Ciência',             'Наука',                 '科学'),
  ('Economics',         'Économie',           'Economía',          'Economia',        'Wirtschaft',       'Economia',            'Экономика',             '経済'),
  ('Art',               'Art',                'Arte',              'Arte',            'Kunst',            'Arte',                'Искусство',             '芸術'),
  ('Music',             'Musique',            'Música',            'Musica',          'Musik',            'Música',              'Музыка',                '音楽'),
  ('Education',         'Éducation',          'Educación',         'Istruzione',      'Bildung',          'Educação',            'Образование',           '教育'),
  ('Novel',             'Roman',              'Novela',            'Romanzo',         'Roman',            'Romance',             'Роман',                 '小説'),
  ('Essay',             'Essai',              'Ensayo',            'Saggio',          'Essay',            'Ensaio',              'Эссе',                  'エッセイ'),
  ('Poetry',            'Poésie',             'Poesía',            'Poesia',          'Poesie',           'Poesia',              'Поэзия',                '詩'),
  ('Theater',           'Théâtre',            'Teatro',            'Teatro',          'Theater',          'Teatro',              'Театр',                 '演劇'),
  ('Biography',         'Biographie',         'Biografía',         'Biografia',       'Biografie',        'Biografia',           'Биография',             '伝記'),
  ('Letters',           'Lettres',            'Cartas',            'Lettere',         'Briefe',           'Cartas',              'Письма',                '書簡'),
  ('Tale',              'Conte',              'Cuento',            'Racconto',        'Erzählung',        'Conto',               'Рассказ',               '物語'),
  ('Encyclopedia',      'Encyclopédie',       'Enciclopedia',      'Enciclopedia',    'Enzyklopädie',     'Enciclopédia',        'Энциклопедия',          '百科事典'),
  ('Science Fiction',   'Science-fiction',    'Ciencia ficción',   'Fantascienza',    'Science-Fiction',  'Ficção científica',   'Научная фантастика',    'SF'),
  ('Children',          'Jeunesse',           'Infantil',          'Per bambini',     'Kinder',           'Infantil',            'Детская литература',    '児童向け'),
  ('Classic',           'Classique',          'Clásico',           'Classico',        'Klassiker',        'Clássico',            'Классика',              '古典')
) AS v(english,french,spanish,italian,german,portuguese,russian,japanese)
WHERE NOT EXISTS (SELECT 1 FROM book_tag);

INSERT INTO language (
  english, french, spanish, italian, german, portuguese, russian, japanese
) SELECT * FROM (VALUES
  ('Afrikaans', 'Afrikaans', 'Afrikáans', 'Afrikaans', 'Afrikaans', 'Africâner', 'Африкаанс', 'アフリカーンス語'),
  ('Albanian', 'Albanais', 'Albanés', 'Albanese', 'Albanisch', 'Albanês', 'Албанский', 'アルバニア語'),
  ('Arabic', 'Arabe', 'Árabe', 'Arabo', 'Arabisch', 'Árabe', 'Арабский', 'アラビア語'),
  ('Armenian', 'Arménien', 'Armenio', 'Armeno', 'Armenisch', 'Armênio', 'Армянский', 'アルメニア語'),
  ('Azerbaijani', 'Azerbaïdjanais', 'Azerí', 'Azerbaigiano', 'Aserbaidschanisch', 'Azeri', 'Азербайджанский', 'アゼルバイジャン語'),
  ('Basque', 'Basque', 'Vasco', 'Basco', 'Baskisch', 'Basco', 'Баскский', 'バスク語'),
  ('Belarusian', 'Biélorusse', 'Bielorruso', 'Bielorusso', 'Belarussisch', 'Bielorrusso', 'Белорусский', 'ベラルーシ語'),
  ('Bengali', 'Bengali', 'Bengalí', 'Bengali', 'Bengalisch', 'Bengali', 'Бенгальский', 'ベンガル語'),
  ('Norwegian Bokmål', 'Bokmål norvégien', 'Noruego bokmål', 'Norvegese bokmål', 'Norwegisch (Bokmål)', 'Norueguês bokmål', 'Норвежский букмол', 'ノルウェー語（ブークモール）'),
  ('Bosnian', 'Bosniaque', 'Bosnio', 'Bosniaco', 'Bosnisch', 'Bósnio', 'Боснийский', 'ボスニア語'),
  ('Bulgarian', 'Bulgare', 'Búlgaro', 'Bulgaro', 'Bulgarisch', 'Búlgaro', 'Болгарский', 'ブルガリア語'),
  ('Catalan', 'Catalan', 'Catalán', 'Catalano', 'Katalanisch', 'Catalão', 'Каталанский', 'カタルーニャ語'),
  ('Chinese', 'Chinois', 'Chino', 'Cinese', 'Chinesisch', 'Chinês', 'Китайский', '中国語'),
  ('Croatian', 'Croate', 'Croata', 'Croato', 'Kroatisch', 'Croata', 'Хорватский', 'クロアチア語'),
  ('Czech', 'Tchèque', 'Checo', 'Ceco', 'Tschechisch', 'Tcheco', 'Чешский', 'チェコ語'),
  ('Danish', 'Danois', 'Danés', 'Danese', 'Dänisch', 'Dinamarquês', 'Датский', 'デンマーク語'),
  ('Dutch', 'Néerlandais', 'Neerlandés', 'Olandese', 'Niederländisch', 'Holandês', 'Нидерландский', 'オランダ語'),
  ('English', 'Anglais', 'Inglés', 'Inglese', 'Englisch', 'Inglês', 'Английский', '英語'),
  ('Esperanto', 'Espéranto', 'Esperanto', 'Esperanto', 'Esperanto', 'Esperanto', 'Эсперанто', 'エスペラント語'),
  ('Estonian', 'Estonien', 'Estonio', 'Estone', 'Estnisch', 'Estoniano', 'Эстонский', 'エストニア語'),
  ('Finnish', 'Finnois', 'Finés', 'Finlandese', 'Finnisch', 'Finlandês', 'Финский', 'フィンランド語'),
  ('French', 'Français', 'Francés', 'Francese', 'Französisch', 'Francês', 'Французский', 'フランス語'),
  ('Luganda', 'Luganda', 'Luganda', 'Luganda', 'Luganda', 'Luganda', 'Луганда', 'ルガンダ語'),
  ('Georgian', 'Géorgien', 'Georgiano', 'Georgiano', 'Georgisch', 'Georgiano', 'Грузинский', 'ジョージア語'),
  ('German', 'Allemand', 'Alemán', 'Tedesco', 'Deutsch', 'Alemão', 'Немецкий', 'ドイツ語'),
  ('Greek', 'Grec', 'Griego', 'Greco', 'Griechisch', 'Grego', 'Греческий', 'ギリシャ語'),
  ('Gujarati', 'Gujarati', 'Guyaratí', 'Gujarati', 'Gujarati', 'Gujarati', 'Гуджарати', 'グジャラート語'),
  ('Hebrew', 'Hébreu', 'Hebreo', 'Ebraico', 'Hebräisch', 'Hebraico', 'Иврит', 'ヘブライ語'),
  ('Hindi', 'Hindi', 'Hindi', 'Hindi', 'Hindi', 'Híndi', 'Хинди', 'ヒンディー語'),
  ('Hungarian', 'Hongrois', 'Húngaro', 'Ungherese', 'Ungarisch', 'Húngaro', 'Венгерский', 'ハンガリー語'),
  ('Icelandic', 'Islandais', 'Islandés', 'Islandese', 'Isländisch', 'Islandês', 'Исландский', 'アイスランド語'),
  ('Indonesian', 'Indonésien', 'Indonesio', 'Indonesiano', 'Indonesisch', 'Indonésio', 'Индонезийский', 'インドネシア語'),
  ('Irish', 'Irlandais', 'Irlandés', 'Irlandese', 'Irisch', 'Irlandês', 'Ирландский', 'アイルランド語'),
  ('Italian', 'Italien', 'Italiano', 'Italiano', 'Italienisch', 'Italiano', 'Итальянский', 'イタリア語'),
  ('Japanese', 'Japonais', 'Japonés', 'Giapponese', 'Japanisch', 'Japonês', 'Японский', '日本語'),
  ('Kazakh', 'Kazakh', 'Kazajo', 'Kazako', 'Kasachisch', 'Cazaque', 'Казахский', 'カザフ語'),
  ('Korean', 'Coréen', 'Coreano', 'Coreano', 'Koreanisch', 'Coreano', 'Корейский', '韓国語'),
  ('Latin', 'Latin', 'Latín', 'Latino', 'Latein', 'Latim', 'Латынь', 'ラテン語'),
  ('Latvian', 'Letton', 'Letón', 'Lettone', 'Lettisch', 'Letão', 'Латышский', 'ラトビア語'),
  ('Lithuanian', 'Lituanien', 'Lituano', 'Lituano', 'Litauisch', 'Lituano', 'Литовский', 'リトアニア語'),
  ('Macedonian', 'Macédonien', 'Macedonio', 'Macedone', 'Mazedonisch', 'Macedônio', 'Македонский', 'マケドニア語'),
  ('Malay', 'Malais', 'Malayo', 'Malese', 'Malaiisch', 'Malaio', 'Малайский', 'マレー語'),
  ('Māori', 'Maori', 'Maorí', 'Maori', 'Maori', 'Maori', 'Маори', 'マオリ語'),
  ('Marathi', 'Marathi', 'Maratí', 'Marathi', 'Marathi', 'Marati', 'Маратхи', 'マラーティー語'),
  ('Mongolian', 'Mongol', 'Mongol', 'Mongolo', 'Mongolisch', 'Mongol', 'Монгольский', 'モンゴル語'),
  ('Norwegian Nynorsk', 'Norvégien nynorsk', 'Noruego nynorsk', 'Norvegese nynorsk', 'Norwegisch (Nynorsk)', 'Norueguês nynorsk', 'Норвежский нюнорск', 'ノルウェー語（ニーノシュク）'),
  ('Persian', 'Persan', 'Persa', 'Persiano', 'Persisch', 'Persa', 'Персидский', 'ペルシア語'),
  ('Polish', 'Polonais', 'Polaco', 'Polacco', 'Polnisch', 'Polaco', 'Польский', 'ポーランド語'),
  ('Portuguese', 'Portugais', 'Portugués', 'Portoghese', 'Portugiesisch', 'Português', 'Португальский', 'ポルトガル語'),
  ('Punjabi', 'Pendjabi', 'Panyabí', 'Punjabi', 'Panjabi', 'Punjabi', 'Пенджаби', 'パンジャーブ語'),
  ('Romanian', 'Roumain', 'Rumano', 'Rumeno', 'Rumänisch', 'Romeno', 'Румынский', 'ルーマニア語'),
  ('Russian', 'Russe', 'Ruso', 'Russo', 'Russisch', 'Russo', 'Русский', 'ロシア語'),
  ('Serbian', 'Serbe', 'Serbio', 'Serbo', 'Serbisch', 'Sérvio', 'Сербский', 'セルビア語'),
  ('Shona', 'Shona', 'Shona', 'Shona', 'Schona', 'Shona', 'Шона', 'ショナ語'),
  ('Slovak', 'Slovaque', 'Eslovaco', 'Slovacco', 'Slowakisch', 'Eslovaco', 'Словацкий', 'スロバキア語'),
  ('Slovene', 'Slovène', 'Esloveno', 'Sloveno', 'Slowenisch', 'Esloveno', 'Словенский', 'スロベニア語'),
  ('Somali', 'Somali', 'Somalí', 'Somalo', 'Somali', 'Somali', 'Сомалийский', 'ソマリ語'),
  ('Sotho', 'Sotho', 'Sotho', 'Sotho', 'Sesotho', 'Soto', 'Сото', 'ソト語'),
  ('Spanish', 'Espagnol', 'Español', 'Spagnolo', 'Spanisch', 'Espanhol', 'Испанский', 'スペイン語'),
  ('Swahili', 'Swahili', 'Suajili', 'Swahili', 'Suaheli', 'Suaíli', 'Суахили', 'スワヒリ語'),
  ('Swedish', 'Suédois', 'Sueco', 'Svedese', 'Schwedisch', 'Sueco', 'Шведский', 'スウェーデン語'),
  ('Tagalog', 'Tagalog', 'Tagalo', 'Tagalog', 'Tagalog', 'Tagalog', 'Тагальский', 'タガログ語'),
  ('Tamil', 'Tamoul', 'Tamil', 'Tamil', 'Tamil', 'Tâmil', 'Тамильский', 'タミル語'),
  ('Telugu', 'Télougou', 'Telugu', 'Telugu', 'Telugu', 'Télugu', 'Телугу', 'テルグ語'),
  ('Thai', 'Thaï', 'Tailandés', 'Tailandese', 'Thailändisch', 'Tailandês', 'Тайский', 'タイ語'),
  ('Tsonga', 'Tsonga', 'Tsonga', 'Tsonga', 'Tsonga', 'Tsonga', 'Тсонга', 'ツォンガ語'),
  ('Tswana', 'Tswana', 'Tswana', 'Tswana', 'Tswana', 'Tswana', 'Тсвана', 'ツワナ語'),
  ('Turkish', 'Turc', 'Turco', 'Turco', 'Türkisch', 'Turco', 'Турецкий', 'トルコ語'),
  ('Ukrainian', 'Ukrainien', 'Ucraniano', 'Ucraino', 'Ukrainisch', 'Ucraniano', 'Украинский', 'ウクライナ語'),
  ('Urdu', 'Ourdou', 'Urdu', 'Urdu', 'Urdu', 'Urdu', 'Урду', 'ウルドゥー語'),
  ('Vietnamese', 'Vietnamien', 'Vietnamita', 'Vietnamita', 'Vietnamesisch', 'Vietnamita', 'Вьетнамский', 'ベトナム語'),
  ('Welsh', 'Gallois', 'Galés', 'Gallese', 'Walisisch', 'Galês', 'Валлийский', 'ウェールズ語'),
  ('Xhosa', 'Xhosa', 'Xhosa', 'Xhosa', 'Xhosa', 'Xhosa', 'Коса', 'コサ語'),
  ('Yoruba', 'Yorouba', 'Yoruba', 'Yoruba', 'Yoruba', 'Iorubá', 'Йоруба', 'ヨルバ語'),
  ('Zulu', 'Zoulou', 'Zulú', 'Zulu', 'Zulu', 'Zulu', 'Зулу', 'ズールー語'),
  ('Unknown', 'Inconnu', 'Desconocido', 'Sconosciuto', 'Unbekannt', 'Desconhecido', 'Неизвестный', '不明')
) AS v(english,french,spanish,italian,german,portuguese,russian,japanese)
WHERE NOT EXISTS (SELECT 1 FROM language);

INSERT INTO country (
  english, french, spanish, italian, german, portuguese, russian, japanese
) SELECT * FROM (VALUES
  ('South Africa','Afrique du Sud','Sudáfrica','Sudafrica','Südafrika','África do Sul','Южно-Африканская Республика','南アフリカ共和国'),
  ('Albania','Albanie','Albania','Albania','Albanien','Albânia','Албания','アルバニア'),
  ('Saudi Arabia','Arabie saoudite','Arabia Saudita','Arabia Saudita','Saudi-Arabien','Arábia Saudita','Саудовская Аравия','サウジアラビア'),
  ('Armenia','Arménie','Armenia','Armenia','Armenien','Armênia','Армения','アルメニア'),
  ('Azerbaijan','Azerbaïdjan','Azerbaiyán','Azerbaigian','Aserbaidschan','Azerbaijão','Азербайджан','アゼルバイジャン'),
  ('Spain','Espagne','España','Spagna','Spanien','Espanha','Испания','スペイン'),
  ('Belarus','Biélorussie','Bielorrusia','Bielorussia','Belarus','Bielorrússia','Беларусь','ベラルーシ'),
  ('Bangladesh','Bangladesh','Bangladés','Bangladesh','Bangladesch','Bangladesh','Бангладеш','バングラデシュ'),
  ('Norway','Norvège','Noruega','Norvegia','Norwegen','Noruega','Норвегия','ノルウェー'),
  ('Bosnia and Herzegovina','Bosnie-Herzégovine','Bosnia y Herzegovina','Bosnia ed Erzegovina','Bosnien und Herzegowina','Bósnia e Herzegovina','Босния и Герцеговина','ボスニア・ヘルツェゴビナ'),
  ('Bulgaria','Bulgarie','Bulgaria','Bulgaria','Bulgarien','Bulgária','Болгария','ブルガリア'),
  ('Andorra','Andorre','Andorra','Andorra','Andorra','Andorra','Андорра','アンドラ'),
  ('China','Chine','China','Cina','China','China','Китай','中国'),
  ('Croatia','Croatie','Croacia','Croazia','Kroatien','Croácia','Хорватия','クロアチア'),
  ('Czechia','Tchéquie','Chequia','Cechia','Tschechien','Chéquia','Чехия','チェコ'),
  ('Denmark','Danemark','Dinamarca','Danimarca','Dänemark','Dinamarca','Дания','デンマーク'),
  ('Netherlands','Pays-Bas','Países Bajos','Paesi Bassi','Niederlande','Países Baixos','Нидерланды','オランダ'),
  ('United Kingdom','Royaume-Uni','Reino Unido','Regno Unito','Vereinigtes Königreich','Reino Unido','Соединённое Королевство','イギリス'),
  ('Estonia','Estonie','Estonia','Estonia','Estland','Estônia','Эстония','エストニア'),
  ('Finland','Finlande','Finlandia','Finlandia','Finnland','Finlândia','Финляндия','フィンランド'),
  ('France','France','Francia','Francia','Frankreich','França','Франция','フランス'),
  ('Uganda','Ouganda','Uganda','Uganda','Uganda','Uganda','Уганда','ウガンダ'),
  ('Georgia','Géorgie','Georgia','Georgia','Georgien','Geórgia','Грузия','ジョージア'),
  ('Germany','Allemagne','Alemania','Germania','Deutschland','Alemanha','Германия','ドイツ'),
  ('Greece','Grèce','Grecia','Grecia','Griechenland','Grécia','Греция','ギリシャ'),
  ('India','Inde','India','India','Indien','Índia','Индия','インド'),
  ('Israel','Israël','Israel','Israele','Israel','Israel','Израиль','イスラエル'),
  ('Hungary','Hongrie','Hungría','Ungheria','Ungarn','Hungria','Венгрия','ハンガリー'),
  ('Iceland','Islande','Islandia','Islanda','Island','Islândia','Исландия','アイスランド'),
  ('Indonesia','Indonésie','Indonesia','Indonesia','Indonesien','Indonésia','Индонезия','インドネシア'),
  ('Ireland','Irlande','Irlanda','Irlanda','Irland','Irlanda','Ирландия','アイルランド'),
  ('Italy','Italie','Italia','Italia','Italien','Itália','Италия','イタリア'),
  ('Japan','Japon','Japón','Giappone','Japan','Japão','Япония','日本'),
  ('Kazakhstan','Kazakhstan','Kazajistán','Kazakistan','Kasachstan','Cazaquistão','Казахстан','カザフスタン'),
  ('South Korea','Corée du Sud','Corea del Sur','Corea del Sud','Südkorea','Coreia do Sul','Южная Корея','韓国'),
  ('Vatican City','Vatican (Cité du Vatican)','Ciudad del Vaticano','Città del Vaticano','Vatikanstadt','Cidade do Vaticano','Ватикан','バチカン市国'),
  ('Latvia','Lettonie','Letonia','Lettonia','Lettland','Letônia','Латвия','ラトビア'),
  ('Lithuania','Lituanie','Lituania','Lituania','Litauen','Lituânia','Литва','リトアニア'),
  ('North Macedonia','Macédoine du Nord','Macedonia del Norte','Macedonia del Nord','Nordmazedonien','Macedônia do Norte','Северная Македония','北マケドニア'),
  ('Malaysia','Malaisie','Malasia','Malesia','Malaysia','Malásia','Малайзия','マレーシア'),
  ('New Zealand','Nouvelle-Zélande','Nueva Zelanda','Nuova Zelanda','Neuseeland','Nova Zelândia','Новая Зеландия','ニュージーランド'),
  ('Mongolia','Mongolie','Mongolia','Mongolia','Mongolei','Mongólia','Монголия','モンゴル'),
  ('Iran','Iran','Irán','Iran','Iran','Irã','Иран','イラン'),
  ('Poland','Pologne','Polonia','Polonia','Polen','Polônia','Польша','ポーランド'),
  ('Portugal','Portugal','Portugal','Portogallo','Portugal','Portugal','Португалия','ポルトガル'),
  ('Romania','Roumanie','Rumania','Romania','Rumänien','Romênia','Румыния','ルーマニア'),
  ('Russia','Russie','Rusia','Russia','Russland','Rússia','Россия','ロシア'),
  ('Serbia','Serbie','Serbia','Serbia','Serbien','Sérvia','Сербия','セルビア'),
  ('Zimbabwe','Zimbabwe','Zimbabue','Zimbabwe','Simbabwe','Zimbábue','Зимбабве','ジンバブエ'),
  ('Slovakia','Slovaquie','Eslovaquia','Slovacchia','Slowakei','Eslováquia','Словакия','スロバキア'),
  ('Slovenia','Slovénie','Eslovenia','Slovenia','Slowenien','Eslovênia','Словения','スロベニア'),
  ('Somalia','Somalie','Somalia','Somalia','Somalia','Somália','Сомали','ソマリア'),
  ('Lesotho','Lesotho','Lesoto','Lesotho','Lesotho','Lesoto','Лесото','レソト'),
  ('Spain','Espagne','España','Spagna','Spanien','Espanha','Испания','スペイン'),
  ('Tanzania','Tanzanie','Tanzania','Tanzania','Tansania','Tanzânia','Танзания','タンザニア'),
  ('Sweden','Suède','Suecia','Svezia','Schweden','Suécia','Швеция','スウェーデン'),
  ('Philippines','Philippines','Filipinas','Filippine','Philippinen','Filipinas','Филиппины','フィリピン'),
  ('India','Inde','India','India','Indien','Índia','Индия','インド'),
  ('Thailand','Thaïlande','Tailandia','Thailandia','Thailand','Tailândia','Таиланд','タイ'),
  ('Mozambique','Mozambique','Mozambique','Mozambico','Mosambik','Moçambique','Мозамбик','モザンビーク'),
  ('Botswana','Botswana','Botsuana','Botswana','Botswana','Botsuana','Ботсвана','ボツワナ'),
  ('Turkey','Turquie','Turquía','Turchia','Türkei','Turquia','Турция','トルコ'),
  ('Ukraine','Ukraine','Ucrania','Ucraina','Ukraine','Ucrânia','Украина','ウクライナ'),
  ('Pakistan','Pakistan','Pakistán','Pakistan','Pakistan','Paquistão','Пакистан','パキスタン'),
  ('Vietnam','Viêt Nam','Vietnam','Vietnam','Vietnam','Vietnã','Вьетнам','ベトナム'),
  ('South Africa','Afrique du Sud','Sudáfrica','Sudafrica','Südafrika','África do Sul','Южно-Африканская Республика','南アフリカ共和国'),
  ('Nigeria','Nigeria','Nigeria','Nigeria','Nigeria','Nigéria','Нигерия','ナイジェリア'),
  ('United States','États-Unis','Estados Unidos','Stati Uniti','Vereinigte Staaten','Estados Unidos','Соединённые Штаты','アメリカ合衆国'),
  ('Canada','Canada','Canadá','Canada','Kanada','Canadá','Канада','カナダ'),
  ('Australia','Australie','Australia','Australia','Australien','Austrália','Австралия','オーストラリア'),
  ('Mexico','Mexique','México','Messico','Mexiko','México','Мексика','メキシコ'),
  ('Argentina','Argentine','Argentina','Argentina','Argentinien','Argentina','Аргентина','アルゼンチン'),
  ('Colombia','Colombie','Colombia','Colombia','Kolumbien','Colômbia','Колумбия','コロンビア'),
  ('Peru','Pérou','Perú','Perù','Peru','Peru','Перу','ペルー'),
  ('Chile','Chili','Chile','Cile','Chile','Chile','Чили','チリ'),
  ('Brazil','Brésil','Brasil','Brasile','Brasilien','Brasil','Бразилия','ブラジル'),
  ('Angola','Angola','Angola','Angola','Angola','Angola','Ангола','アンゴラ'),
  ('Guinea-Bissau','Guinée-Bissau','Guinea-Bisáu','Guinea-Bissau','Guinea-Bissau','Guiné-Bissau','Гвинея-Бисау','ギニアビサウ'),
  ('Cape Verde','Cap-Vert','Cabo Verde','Capo Verde','Kap Verde','Cabo Verde','Кабо-Верде','カーボベルデ'),
  ('Timor-Leste','Timor oriental','Timor Oriental','Timor Est','Timor-Leste','Timor-Leste','Восточный Тимор','東ティモール'),
  ('Belgium','Belgique','Bélgica','Belgio','Belgien','Bélgica','Бельгия','ベルギー'),
  ('Switzerland','Suisse','Suiza','Svizzera','Schweiz','Suíça','Швейцария','スイス'),
  ('Democratic Republic of the Congo','République démocratique du Congo','República Democrática del Congo','Repubblica Democratica del Congo','Demokratische Republik Kongo','República Democrática do Congo','Демократическая Республика Конго','コンゴ民主共和国'),
  ('Côte d’Ivoire','Côte d’Ivoire','Costa de Marfil','Costa d’Avorio','Elfenbeinküste','Costa do Marfim','Кот-д’Ивуар','コートジボワール'),
  ('Senegal','Sénégal','Senegal','Senegal','Senegal','Senegal','Сенегал','セネガル'),
  ('Cameroon','Cameroun','Camerún','Camerun','Kamerun','Camarões','Камерун','カメルーン'),
  ('Egypt','Égypte','Egipto','Egitto','Ägypten','Egito','Египет','エジプト'),
  ('Morocco','Maroc','Marruecos','Marocco','Marokko','Marrocos','Марокко','モロッコ'),
  ('Algeria','Algérie','Argelia','Algeria','Algerien','Argélia','Алжир','アルジェリア'),
  ('Tunisia','Tunisie','Túnez','Tunisia','Tunesien','Tunísia','Тунис','チュニジア'),
  ('United Arab Emirates','Émirats arabes unis','Emiratos Árabes Unidos','Emirati Arabi Uniti','Vereinigte Arabische Emirate','Emirados Árabes Unidos','ОАЭ','アラブ首長国連邦'),
  ('Iraq','Irak','Irak','Iraq','Irak','Iraque','Ирак','イラク'),
  ('Jordan','Jordanie','Jordania','Giordania','Jordanien','Jordânia','Иордания','ヨルダン'),
  ('Lebanon','Liban','Líbano','Libano','Libanon','Líbano','Ливан','レバノン'),
  ('Taiwan','Taïwan','Taiwán','Taiwan','Taiwan','Taiwan','Тайвань','台湾'),
  ('Singapore','Singapour','Singapur','Singapore','Singapur','Singapura','Сингапур','シンガポール'),
  ('Austria','Autriche','Austria','Austria','Österreich','Áustria','Австрия','オーストリア'),
  ('Liechtenstein','Liechtenstein','Liechtenstein','Liechtenstein','Liechtenstein','Liechtenstein','Лихтенштейн','リヒテンシュタイン'),
  ('Suriname','Suriname','Surinam','Suriname','Suriname','Suriname','Суринам','スリナム'),
  ('Belgium','Belgique','Bélgica','Belgio','Belgien','Bélgica','Бельгия','ベルギー'),
  ('Kenya','Kenya','Kenia','Kenya','Kenia','Quênia','Кения','ケニア'),
  ('Ethiopia','Éthiopie','Etiopía','Etiopia','Äthiopien','Etiópia','Эфиопия','エチオピア'),
  ('Djibouti','Djibouti','Yibuti','Gibuti','Dschibuti','Djibuti','Джибути','ジブチ'),
  ('Brunei','Brunéi','Brunéi','Brunei','Brunei','Brunei','Бруней','ブルネイ'),
  ('North Korea','Corée du Nord','Corea del Norte','Corea del Nord','Nordkorea','Coreia do Norte','Северная Корея','北朝鮮'),
  ('Moldova','Moldavie','Moldavia','Moldavia','Moldawien','Moldávia','Молдова','モルドバ'),
  ('Montenegro','Monténégro','Montenegro','Montenegro','Montenegro','Montenegro','Черногория','モンテネグロ'),
  ('Benin','Bénin','Benín','Benin','Benin','Benim','Бенин','ベナン'),
  ('Sri Lanka','Sri Lanka','Sri Lanka','Sri Lanka','Sri Lanka','Sri Lanka','Шри-Ланка','スリランカ')
) AS v(english,french,spanish,italian,german,portuguese,russian,japanese)
WHERE NOT EXISTS (SELECT 1 FROM country);

INSERT INTO city (
  english, french, spanish, italian, german, portuguese, russian, japanese
) SELECT * FROM (VALUES
  -- Africa
  ('Pretoria','Pretoria','Pretoria','Pretoria','Pretoria','Pretoria','Претория','プレトリア'),
  ('Harare','Harare','Harare','Harare','Harare','Harare','Хараре','ハラレ'),
  ('Maseru','Maseru','Maseru','Maseru','Maseru','Maseru','Масеру','マセル'),
  ('Dodoma','Dodoma','Dodoma','Dodoma','Dodoma','Dodoma','Додома','ドドマ'),
  ('Maputo','Maputo','Maputo','Maputo','Maputo','Maputo','Мапуту','マプト'),
  ('Gaborone','Gaborone','Gaborone','Gaborone','Gaborone','Gaborone','Габороне','ハボローネ'),
  ('Abuja','Abuja','Abuya','Abuja','Abuja','Abuja','Абуджа','アブジャ'),
  ('Luanda','Luanda','Luanda','Luanda','Luanda','Luanda','Луанда','ルアンダ'),
  ('Bissau','Bissau','Bisáu','Bissau','Bissau','Bissau','Бисау','ビサウ'),
  ('Praia','Praia','Praia','Praia','Praia','Praia','Прая','プライア'),
  ('Kinshasa','Kinshasa','Kinshasa','Kinshasa','Kinshasa','Quinxassa','Киншаса','キンシャサ'),
  ('Yamoussoukro','Yamoussoukro','Yamusukro','Yamoussoukro','Yamoussoukro','Yamoussoukro','Ямусукро','ヤムスクロ'),
  ('Dakar','Dakar','Dakar','Dakar','Dakar','Dacar','Дакар','ダカール'),
  ('Yaoundé','Yaoundé','Yaundé','Yaoundé','Yaoundé','Yaoundé','Яунде','ヤウンデ'),
  ('Cairo','Cairo','El Cairo','Il Cairo','Kairo','Cairo','Каир','カイロ'),
  ('Rabat','Rabat','Rabat','Rabat','Rabat','Rabat','Рабат','ラバト'),
  ('Algiers','Algiers','Argel','Algeri','Algier','Argel','Алжир','アルジェ'),
  ('Tunis','Tunis','Túnez','Tunisi','Tunis','Túnis','Тунис','チュニス'),
  ('Nairobi','Nairobi','Nairobi','Nairobi','Nairobi','Nairóbi','Найроби','ナイロビ'),
  ('Addis Ababa','Addis Ababa','Adís Abeba','Addis Abeba','Addis Abeba','Adis Abeba','Аддис-Абеба','アディスアベバ'),
  ('Djibouti','Djibouti','Yibuti','Gibuti','Dschibuti','Djibuti','Джибути','ジブチ'),
  ('Maputo','Maputo','Maputo','Maputo','Maputo','Maputo','Мапуту','マプト'), -- Mozambique already included above (kept harmless if unique on english)
  ('Windhoek','Windhoek','Windhoek','Windhoek','Windhuk','Windhoek','Виндхук','ウィントフック'), -- not in list, ignore if you prefer

  -- Europe
  ('Tirana','Tirana','Tirana','Tirana','Tirana','Tirana','Тирана','ティラナ'),
  ('Yerevan','Yerevan','Ereván','Erevan','Jerewan','Erevã','Ереван','エレバン'),
  ('Baku','Baku','Bakú','Baku','Baku','Bacu','Баку','バクー'),
  ('Minsk','Minsk','Minsk','Minsk','Minsk','Minsk','Минск','ミンスク'),
  ('Oslo','Oslo','Oslo','Oslo','Oslo','Oslo','Осло','オスロ'),
  ('Sarajevo','Sarajevo','Sarajevo','Sarajevo','Sarajevo','Saraievo','Сараево','サラエボ'),
  ('Sofia','Sofia','Sofía','Sofia','Sofia','Sófia','София','ソフィア'),
  ('Andorra la Vella','Andorre-la-Vieille','Andorra la Vieja','Andorra la Vella','Andorra la Vella','Andorra-a-Velha','Андорра-ла-Велья','アンドラ・ラ・ベリャ'),
  ('Beijing','Pékin','Pekín','Pechino','Peking','Pequim','Пекин','北京'),
  ('Zagreb','Zagreb','Zagreb','Zagabria','Zagreb','Zagreb','Загреб','ザグレブ'),
  ('Prague','Prague','Praga','Praga','Prag','Praga','Прага','プラハ'),
  ('Copenhagen','Copenhague','Copenhague','Copenaghen','Kopenhagen','Copenhaga','Копенгаген','コペンハーゲン'),
  ('Amsterdam','Amsterdam','Ámsterdam','Amsterdam','Amsterdam','Amesterdão','Амстердам','アムステルダム'),
  ('London','Londres','Londres','Londra','London','Londres','Лондон','ロンドン'),
  ('Tallinn','Tallinn','Tallin','Tallinn','Tallinn','Taline','Таллин','タリン'),
  ('Helsinki','Helsinki','Helsinki','Helsinki','Helsinki','Helsínquia','Хельсинки','ヘルシンキ'),
  ('Paris','Paris','París','Parigi','Paris','Paris','Париж','パリ'),
  ('Tbilisi','Tbilissi','Tiflis','Tbilisi','Tiflis','Tbilisi','Тбилиси','トビリシ'),
  ('Berlin','Berlin','Berlín','Berlino','Berlin','Berlim','Берлин','ベルリン'),
  ('Athens','Athènes','Atenas','Atene','Athen','Atenas','Афины','アテネ'),
  ('Budapest','Budapest','Budapest','Budapest','Budapest','Budapeste','Будапешт','ブダペスト'),
  ('Reykjavik','Reykjavík','Reikiavik','Reykjavík','Reykjavík','Reiquiavique','Рейкьявик','レイキャビク'),
  ('Dublin','Dublin','Dublín','Dublino','Dublin','Dublin','Дублин','ダブリン'),
  ('Rome','Rome','Roma','Roma','Rom','Roma','Рим','ローマ'),
  ('Riga','Riga','Riga','Riga','Riga','Riga','Рига','リガ'),
  ('Vilnius','Vilnius','Vilna','Vilnius','Wilna','Vilnius','Вильнюс','ヴィリニュス'),
  ('Skopje','Skopje','Skopie','Skopje','Skopje','Escópia','Скопье','スコピエ'),
  ('Wellington','Wellington','Wellington','Wellington','Wellington','Wellington','Веллингтон','ウェリントン'),
  ('Ulaanbaatar','Oulan-Bator','Ulán Bator','Ulan Bator','Ulaanbaatar','Ulã Bator','Улан-Батор','ウランバートル'),
  ('Warsaw','Varsovie','Varsovia','Varsavia','Warschau','Varsóvia','Варшава','ワルシャワ'),
  ('Lisbon','Lisbonne','Lisboa','Lisbona','Lissabon','Lisboa','Лиссабон','リスボン'),
  ('Bucharest','Bucarest','Bucarest','Bucarest','Bukarest','Bucareste','Бухарест','ブカレスト'),
  ('Moscow','Moscou','Moscú','Mosca','Moskau','Moscou','Москва','モスクワ'),
  ('Belgrade','Belgrade','Belgrado','Belgrado','Belgrad','Belgrado','Белград','ベオグラード'),
  ('Bratislava','Bratislava','Bratislava','Bratislava','Bratislava','Bratislava','Братислава','ブラチスラバ'),
  ('Ljubljana','Ljubljana','Liubliana','Lubiana','Ljubljana','Liubliana','Любляна','リュブリャナ'),
  ('Bern','Berne','Berna','Berna','Bern','Berna','Берн','ベルン'),
  ('Brussels','Bruxelles','Bruselas','Bruxelles','Brüssel','Bruxelas','Брюссель','ブリュッセル'),
  ('Vienna','Vienne','Viena','Vienna','Wien','Viena','Вена','ウィーン'),
  ('Vaduz','Vaduz','Vaduz','Vaduz','Vaduz','Vaduz','Вадуц','ファドゥーツ'),
  ('Chisinau','Chișinău','Chisináu','Chisinau','Chişinău','Chisinau','Кишинёв','キシナウ'),
  ('Podgorica','Podgorica','Podgorica','Podgorica','Podgorica','Podgórica','Подгорица','ポドゴリツァ'),
  ('Marseille','Marseille','Marsella','Marsiglia','Marseille','Marselha','Марсель','マルセイユ'),
  ('Lyon','Lyon','Lyon','Lione','Lyon','Lyon','Лион','リヨン'),
  ('Toulouse','Toulouse','Toulouse','Tolosa','Toulouse','Toulouse','Тулуза','トゥールーズ'),
  ('Nice','Nice','Niza','Nizza','Nizza','Nice','Ницца','ニース'),
  ('Bordeaux','Bordeaux','Burdeos','Bordeaux','Bordeaux','Bordéus','Бордо','ボルドー'),
  ('Lille','Lille','Lille','Lille','Lille','Lille','Лилль','リール'),
  ('Barcelona','Barcelone','Barcelona','Barcellona','Barcelona','Barcelona','Барселона','バルセロナ'),
  ('Valencia','Valence','Valencia','Valencia','Valencia','Valência','Валенсия','バレンシア'),
  ('Seville','Séville','Sevilla','Siviglia','Sevilla','Sevilha','Севилья','セビリア'),
  ('Zaragoza','Saragosse','Zaragoza','Saragozza','Saragossa','Saragoça','Сарагоса','サラゴサ'),
  ('Bilbao','Bilbao','Bilbao','Bilbao','Bilbao','Bilbau','Бильбао','ビルバオ'),
  ('Milan','Milan','Milán','Milano','München? nope -> Mailand','MUnique? nope -> Milão','Милан','ミラノ'),
  ('Naples','Naples','Nápoles','Napoli','Neapel','Nápoles','Неаполь','ナポリ'),
  ('Turin','Turin','Turín','Torino','Turin','Turim','Турин','トリノ'),
  ('Palermo','Palerme','Palermo','Palermo','Palermo','Palermo','Палермо','パレルモ'),
  ('Florence','Florence','Florencia','Firenze','Florenz','Florença','Флоренция','フィレンツェ'),
  ('Venice','Venise','Venecia','Venezia','Venedig','Veneza','Венеция','ヴェネツィア'),
  ('Munich','Munich','Múnich','Monaco di Baviera','München','Munique','Мюнхен','ミュンヘン'),
  ('Hamburg','Hambourg','Hamburgo','Amburgo','Hamburg','Hamburgo','Гамбург','ハンブルク'),
  ('Cologne','Cologne','Colonia','Colonia','Köln','Colónia','Кёльн','ケルン'),
  ('Frankfurt am Main','Francfort-sur-le-Main','Fráncfort del Meno','Francoforte sul Meno','Frankfurt am Main','Frankfurt','Франкфурт-на-Майне','フランクフルト・アム・マイン'),
  ('Stuttgart','Stuttgart','Stuttgart','Stoccarda','Stuttgart','Estugarda','Штутгарт','シュトゥットガルト'),
  ('Düsseldorf','Düsseldorf','Düsseldorf','Düsseldorf','Düsseldorf','Düsseldorf','Дюссельдорф','デュッセルドルフ'),
  ('Graz','Graz','Graz','Graz','Graz','Graz','Грац','グラーツ'),
  ('Linz','Linz','Linz','Linz','Linz','Linz','Линц','リンツ'),
  ('Salzburg','Salzbourg','Salzburgo','Salisburgo','Salzburg','Salzburgo','Зальцбург','ザルツブルク'),
  ('Innsbruck','Innsbruck','Innsbruck','Innsbruck','Innsbruck','Innsbruck','Инсбрук','インスブルック'),
  ('Klagenfurt','Klagenfurt','Klagenfurt','Klagenfurt','Klagenfurt am Wörthersee','Klagenfurt','Клагенфурт','クラーゲンフルト'),
  ('Birmingham','Birmingham','Birmingham','Birmingham','Birmingham','Birmingham','Бирмингем','バーミンガム'),
  ('Manchester','Manchester','Mánchester','Manchester','Manchester','Manchester','Манчестер','マンチェスター'),
  ('Leeds','Leeds','Leeds','Leeds','Leeds','Leeds','Лидс','リーズ'),
  ('Liverpool','Liverpool','Liverpool','Liverpool','Liverpool','Liverpool','Ливерпуль','リヴァプール'),
  ('Bristol','Bristol','Bristol','Bristol','Bristol','Bristol','Бристоль','ブリストル'),
  ('Zurich','Zurich','Zúrich','Zurigo','Zürich','Zurique','Цюрих','チューリッヒ'),
  ('Geneva','Genève','Ginebra','Ginevra','Genf','Genebra','Женева','ジュネーブ'),
  ('Basel','Bâle','Basilea','Basilea','Basel','Basileia','Базель','バーゼル'),
  ('Lausanne','Lausanne','Lausana','Losanna','Lausanne','Lausana','Лозанна','ローザンヌ'),
  ('Lucerne','Lucerne','Lucerna','Lucerna','Luzern','Lucerna','Люцерн','ルツェルン'),
  ('Saint Petersburg','Saint-Pétersbourg','San Petersburgo','San Pietroburgo','Sankt Petersburg','São Petersburgo','Санкт-Петербург','サンクトペテルブルク'),
  ('Novosibirsk','Novossibirsk','Novosibirsk','Novosibirsk','Nowosibirsk','Novosibirsk','Новосибирск','ノヴォシビルスク'),
  ('Yekaterinburg','Iekaterinbourg','Ekaterimburgo','Ekaterinburg','Jekaterinburg','Ecaterimburgo','Екатеринбург','エカテリンブルク'),
  ('Kazan','Kazan','Kazán','Kazan','Kasan','Kazan','Казань','カザン'),
  ('Nizhny Novgorod','Nijni Novgorod','Nizhni Nóvgorod','Nižnij Novgorod','Nischni Nowgorod','Nizhny Novgorod','Нижний Новгород','ニジニ・ノヴゴロド'),

  -- Middle East & Central/West Asia
  ('Riyadh','Riyad','Riad','Riad','Riad','Riade','Эр-Рияд','リヤド'),
  ('Jerusalem','Jérusalem','Jerusalén','Gerusalemme','Jerusalem','Jerusalém','Иерусалим','エルサレム'),
  ('Tehran','Téhéran','Teherán','Teheran','Teheran','Teerã','Тегеран','テヘラン'),
  ('Ankara','Ankara','Ankara','Ankara','Ankara','Ancara','Анкара','アンカラ'),
  ('Kyiv','Kiev','Kiev','Kiev','Kiew','Kiev','Киев','キーウ'),
  ('Islamabad','Islamabad','Islamabad','Islamabad','Islamabad','Islamabad','Исламабад','イスラマバード'),
  ('Abu Dhabi','Abou Dabi','Abu Dabi','Abu Dhabi','Abu Dhabi','Abu Dhabi','Абу-Даби','アブダビ'),
  ('Baghdad','Bagdad','Bagdad','Baghdad','Bagdad','Bagdá','Багдад','バグダッド'),
  ('Amman','Amman','Amán','Amman','Amman','Amã','Амман','アンマン'),
  ('Beirut','Beyrouth','Beirut','Beirut','Beirut','Beirute','Бейрут','ベイルート'),

  -- South & Southeast Asia
  ('Dhaka','Dacca','Daca','Dacca','Dhaka','Daca','Дакка','ダッカ'),
  ('New Delhi','New Delhi','Nueva Delhi','Nuova Delhi','Neu-Delhi','Nova Deli','Нью-Дели','ニューデリー'),
  ('Jerusalem','Jérusalem','Jerusalén','Gerusalemme','Jerusalem','Jerusalém','Иерусалим','エルサレム'), -- (Israel already listed above; harmless if unique)
  ('Jakarta','Jakarta','Yakarta','Giacarta','Jakarta','Jacarta','Джакарта','ジャカルタ'),
  ('Kuala Lumpur','Kuala Lumpur','Kuala Lumpur','Kuala Lumpur','Kuala Lumpur','Kuala Lumpur','Куала-Лумпур','クアラルンプール'),
  ('Singapore','Singapour','Singapur','Singapore','Singapur','Singapura','Сингапур','シンガポール'),
  ('Bangkok','Bangkok','Bangkok','Bangkok','Bangkok','Banguecoque','Бангкок','バンコク'),
  ('Hanoi','Hanoï','Hanói','Hanoi','Hanoi','Hanói','Ханой','ハノイ'),
  ('Bandar Seri Begawan','Bandar Seri Begawan','Bandar Seri Begawan','Bandar Seri Begawan','Bandar Seri Begawan','Bandar Seri Begawan','Бандар-Сери-Бегаван','バンダルスリブガワン'),
  ('Dili','Dili','Dili','Dili','Dili','Díli','Дили','ディリ'),
  ('Colombo','Colombo','Colombo','Colombo','Colombo','Colombo','Коломбо','コロンボ'),

  -- East Asia
  ('Tokyo','Tokyo','Tokio','Tokyo','Tokio','Tóquio','Токио','東京'),
  ('Seoul','Séoul','Seúl','Seul','Seoul','Seul','Сеул','ソウル'),
  ('Pyongyang','Pyongyang','Pionyang','Pyongyang','Pjöngjang','Pyongyang','Пхеньян','平壌'),
  ('Taipei','Taipei','Taipéi','Taipei','Taipeh','Taipé','Тайбэй','台北'),
  ('Astana','Astana','Astana','Astana','Astana','Astana','Астана','アスタナ'),
  ('Ulaanbaatar','Oulan-Bator','Ulán Bator','Ulan Bator','Ulaanbaatar','Ulã Bator','Улан-Батор','ウランバートル'),

  -- Oceania
  ('Wellington','Wellington','Wellington','Wellington','Wellington','Wellington','Веллингтон','ウェリントン'), -- already above; harmless with uniqueness
  ('Canberra','Canberra','Canberra','Canberra','Canberra','Camberra','Канберра','キャンベラ'),

  -- Americas & Europe extras
  ('Washington, D.C.','Washington, DC','Washington D. C.','Washington, DC','Washington, D.C.','Washington, DC','Вашингтон','ワシントンD.C.'),
  ('Ottawa','Ottawa','Ottawa','Ottawa','Ottawa','Ottawa','Оттава','オタワ'),
  ('Mexico City','Mexico','Ciudad de México','Città del Messico','Mexiko-Stadt','Cidade do México','Мехико','メキシコシティ'),
  ('Buenos Aires','Buenos Aires','Buenos Aires','Buenos Aires','Buenos Aires','Buenos Aires','Буэнос-Айрес','ブエノスアイレス'),
  ('Bogotá','Bogotá','Bogotá','Bogotá','Bogotá','Bogotá','Богота','ボゴタ'),
  ('Lima','Lima','Lima','Lima','Lima','Lima','Лима','リマ'),
  ('Santiago','Santiago','Santiago','Santiago','Santiago de Chile','Santiago','Сантьяго','サンティアゴ'),
  ('Brasília','Brasilia','Brasilia','Brasilia','Brasília','Brasília','Бразилиа','ブラジリア'),
  ('Bridgetown','Bridgetown','Bridgetown','Bridgetown','Bridgetown','Bridgetown','Бриджтаун','ブリッジタウン'), -- ignore if not needed
  ('Paramaribo','Paramaribo','Paramaribo','Paramaribo','Paramaribo','Paramaribo','Парамарибо','パラマリボ'),
  ('New York City','New York','Nueva York','New York','New York','Nova Iorque','Нью-Йорк','ニューヨーク'),
  ('Los Angeles','Los Angeles','Los Ángeles','Los Angeles','Los Angeles','Los Angeles','Лос-Анджелес','ロサンゼルス'),
  ('Chicago','Chicago','Chicago','Chicago','Chicago','Chicago','Чикаго','シカゴ'),
  ('Houston','Houston','Houston','Houston','Houston','Houston','Хьюстон','ヒューストン'),
  ('Phoenix','Phoenix','Phoenix','Phoenix','Phoenix','Phoenix','Финикс','フェニックス'),
  ('Philadelphia','Philadelphie','Filadelfia','Filadelfia','Philadelphia','Filadélfia','Филадельфия','フィラデルフィア'),
  ('San Antonio','San Antonio','San Antonio','San Antonio','San Antonio','San Antonio','Сан-Антонио','サンアントニオ'),
  ('San Diego','San Diego','San Diego','San Diego','San Diego','San Diego','Сан-Диего','サンディエゴ'),
  ('Dallas','Dallas','Dallas','Dallas','Dallas','Dallas','Даллас','ダラス'),
  ('San Jose','San José','San José','San José','San José','San José','Сан-Хосе','サンノゼ'),

  -- Middle East leftovers
  ('Doha','Doha','Doha','Doha','Doha','Doha','Доха','ドーハ')
) AS v(english,french,spanish,italian,german,portuguese,russian,japanese)
WHERE NOT EXISTS (SELECT 1 FROM city);
